import tempfile
import unittest
from pathlib import Path

from unittest.mock import patch

from arkts_smell_refactor.gate import _changed_current_lines, _fresh_copy, _owner_at_line, _sync_production_changes, refactor_gate


class GateTests(unittest.TestCase):
    def test_refactor_prompt_is_inline_and_model_is_configurable(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); source = root / "source"; task_dir = root / "task"
            target = source / "feature/src/main/ets/Foo.ets"
            target.parent.mkdir(parents=True); target.write_text("export class Foo {}", encoding="utf-8")
            task_dir.mkdir(); (task_dir / "task.json").write_text(
                '{"task_id":"T","workspace_root":"' + str(source) + '","target":{"file_path":"feature/src/main/ets/Foo.ets"}}',
                encoding="utf-8",
            )
            (task_dir / "refactor-prompt.md").write_text("full prompt", encoding="utf-8")
            with patch("arkts_smell_refactor.gate.subprocess.run") as run, patch(
                "arkts_smell_refactor.gate._sync_production_changes", return_value=0
            ):
                run.return_value.returncode = 0
                self.assertEqual(0, refactor_gate(task_dir, source, Path("deveco"), model="provider/model"))
                command = run.call_args.args[0]
                self.assertIn("provider/model", command)
                self.assertEqual("full prompt", command[-1])
                self.assertNotIn("-f", command)

    def test_smell_identity_distinguishes_same_method_name_by_owner(self):
        source = """class TotalCashMapper {
  static getTotalCash() {}
}
class OrderVM {
  getTotalCash() {}
}
"""
        self.assertEqual("TotalCashMapper", _owner_at_line(source, 2, "File"))
        self.assertEqual("OrderVM", _owner_at_line(source, 5, "File"))

    def test_refactor_workspace_physically_excludes_tests(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "mirror"
            main = source / "feature/src/main/ets/Foo.ets"
            local_test = source / "feature/src/test/Foo.test.ets"
            device_test = source / "feature/src/ohosTest/ets/Foo.test.ets"
            for path in (main, local_test, device_test):
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text("code", encoding="utf-8")
            _fresh_copy(source, mirror, exclude_tests=True)
            self.assertTrue((mirror / "feature/src/main/ets/Foo.ets").exists())
            self.assertFalse((mirror / "feature/src/test").exists())
            self.assertFalse((mirror / "feature/src/ohosTest").exists())

    def test_only_production_code_is_synchronized(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "task/refactor-workspace"
            source_file = source / "feature/src/main/ets/Foo.ets"
            mirror_file = mirror / "feature/src/main/ets/Foo.ets"
            source_file.parent.mkdir(parents=True)
            mirror_file.parent.mkdir(parents=True)
            source_file.write_text("before", encoding="utf-8")
            mirror_file.write_text("after", encoding="utf-8")
            self.assertEqual(0, _sync_production_changes(mirror, source))
            self.assertEqual("after", source_file.read_text(encoding="utf-8"))
            baseline = mirror.parent / "baseline-production/feature/src/main/ets/Foo.ets"
            self.assertEqual("before", baseline.read_text(encoding="utf-8"))

    def test_hvigor_generated_build_profile_does_not_reject_source_changes(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "task/refactor-workspace"
            source_file = source / "feature/src/main/ets/Foo.ets"
            mirror_file = mirror / "feature/src/main/ets/Foo.ets"
            generated = mirror / "feature/BuildProfile.ets"
            source_file.parent.mkdir(parents=True)
            mirror_file.parent.mkdir(parents=True)
            generated.parent.mkdir(parents=True, exist_ok=True)
            source_file.write_text("before", encoding="utf-8")
            mirror_file.write_text("after", encoding="utf-8")
            generated.write_text("generated by hvigor", encoding="utf-8")

            self.assertEqual(0, _sync_production_changes(mirror, source))
            self.assertEqual("after", source_file.read_text(encoding="utf-8"))
            self.assertFalse((source / "feature/BuildProfile.ets").exists())

    def test_hvigor_generated_lock_file_does_not_reject_source_changes(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "task/refactor-workspace"
            source_file = source / "feature/src/main/ets/Foo.ets"
            mirror_file = mirror / "feature/src/main/ets/Foo.ets"
            generated = mirror / "feature/oh-package-lock.json5"
            source_file.parent.mkdir(parents=True)
            mirror_file.parent.mkdir(parents=True)
            generated.parent.mkdir(parents=True, exist_ok=True)
            source_file.write_text("before", encoding="utf-8")
            mirror_file.write_text("after", encoding="utf-8")
            generated.write_text("generated by ohpm", encoding="utf-8")

            self.assertEqual(0, _sync_production_changes(mirror, source))
            self.assertEqual("after", source_file.read_text(encoding="utf-8"))
            self.assertFalse((source / "feature/oh-package-lock.json5").exists())

    def test_module_index_is_synchronized_as_production_source(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "task/refactor-workspace"
            source_file = source / "feature/Index.ets"
            mirror_file = mirror / "feature/Index.ets"
            source_file.parent.mkdir(parents=True)
            mirror_file.parent.mkdir(parents=True)
            source_file.write_text("export before", encoding="utf-8")
            mirror_file.write_text("export after", encoding="utf-8")

            self.assertEqual(0, _sync_production_changes(mirror, source))
            self.assertEqual("export after", source_file.read_text(encoding="utf-8"))

    def test_review_pack_includes_direct_relative_production_dependency(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "task/refactor-workspace"
            source_page = source / "feature/src/main/ets/pages/Page.ets"
            mirror_page = mirror / "feature/src/main/ets/pages/Page.ets"
            dependency = source / "feature/src/main/ets/viewModels/PageVM.ets"
            source_page.parent.mkdir(parents=True)
            mirror_page.parent.mkdir(parents=True)
            dependency.parent.mkdir(parents=True)
            source_page.write_text("export class Page {}", encoding="utf-8")
            mirror_page.write_text(
                "import { PageVM } from '../viewModels/PageVM'\nexport class Page { vm: PageVM }",
                encoding="utf-8",
            )
            dependency.write_text("export class PageVM { copy(): void {} }", encoding="utf-8")

            self.assertEqual(0, _sync_production_changes(mirror, source))
            packed = mirror.parent / "review-context-production/feature/src/main/ets/viewModels/PageVM.ets"
            self.assertTrue(packed.exists())
            self.assertIn("copy", packed.read_text(encoding="utf-8"))

    def test_test_build_cache_is_excluded_from_refactor_workspace(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "mirror"
            main = source / "module/src/main/ets/Foo.ets"
            cache = source / "module/.test/default/cache/compiler.msgpack"
            for path in (main, cache):
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text("data", encoding="utf-8")
            _fresh_copy(source, mirror, exclude_tests=True)
            self.assertTrue((mirror / "module/src/main/ets/Foo.ets").exists())
            self.assertFalse((mirror / "module/.test").exists())

    def test_changed_line_detection_ignores_preexisting_linter_lines(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            before = root / "before.ets"
            after = root / "after.ets"
            before.write_text("old warning\nkeep\nbefore\n", encoding="utf-8")
            after.write_text("old warning\nkeep\nafter\n", encoding="utf-8")
            self.assertNotIn(1, _changed_current_lines(before, after))
            self.assertIn(3, _changed_current_lines(before, after))


if __name__ == "__main__":
    unittest.main()
