import tempfile
import unittest
from pathlib import Path

from arkts_smell_refactor.gate import _fresh_copy, _sync_production_changes


class GateTests(unittest.TestCase):
    def test_refactor_workspace_physically_excludes_tests(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "mirror"
            main = source / "feature/src/main/ets/Foo.ets"
            local_test = source / "feature/src/test/Foo.test.ets"
            device_test = source / "feature/src/ohosTest/ets/Foo.test.ets"
            for path in (main, local_test, device_test):
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text("code", encoding="utf-8")
            _fresh_copy(source, mirror, exclude_tests=True)
            self.assertTrue((mirror / "feature/src/main/ets/Foo.ets").exists())
            self.assertFalse((mirror / "feature/src/test").exists())
            self.assertFalse((mirror / "feature/src/ohosTest").exists())

    def test_only_production_code_is_synchronized(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "task/refactor-workspace"
            source_file = source / "feature/src/main/ets/Foo.ets"
            mirror_file = mirror / "feature/src/main/ets/Foo.ets"
            source_file.parent.mkdir(parents=True)
            mirror_file.parent.mkdir(parents=True)
            source_file.write_text("before", encoding="utf-8")
            mirror_file.write_text("after", encoding="utf-8")
            self.assertEqual(0, _sync_production_changes(mirror, source))
            self.assertEqual("after", source_file.read_text(encoding="utf-8"))
            baseline = mirror.parent / "baseline-production/feature/src/main/ets/Foo.ets"
            self.assertEqual("before", baseline.read_text(encoding="utf-8"))

    def test_hvigor_generated_build_profile_does_not_reject_source_changes(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "task/refactor-workspace"
            source_file = source / "feature/src/main/ets/Foo.ets"
            mirror_file = mirror / "feature/src/main/ets/Foo.ets"
            generated = mirror / "feature/BuildProfile.ets"
            source_file.parent.mkdir(parents=True)
            mirror_file.parent.mkdir(parents=True)
            generated.parent.mkdir(parents=True, exist_ok=True)
            source_file.write_text("before", encoding="utf-8")
            mirror_file.write_text("after", encoding="utf-8")
            generated.write_text("generated by hvigor", encoding="utf-8")

            self.assertEqual(0, _sync_production_changes(mirror, source))
            self.assertEqual("after", source_file.read_text(encoding="utf-8"))
            self.assertFalse((source / "feature/BuildProfile.ets").exists())


if __name__ == "__main__":
    unittest.main()
