import tempfile
import unittest
from pathlib import Path

from arkts_smell_refactor.gate import _changed_current_lines, _fresh_copy, _sync_production_changes


class GateTests(unittest.TestCase):
    def test_refactor_workspace_physically_excludes_tests(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "mirror"
            main = source / "feature/src/main/ets/Foo.ets"
            local_test = source / "feature/src/test/Foo.test.ets"
            device_test = source / "feature/src/ohosTest/ets/Foo.test.ets"
            for path in (main, local_test, device_test):
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text("code", encoding="utf-8")
            _fresh_copy(source, mirror, exclude_tests=True)
            self.assertTrue((mirror / "feature/src/main/ets/Foo.ets").exists())
            self.assertFalse((mirror / "feature/src/test").exists())
            self.assertFalse((mirror / "feature/src/ohosTest").exists())

    def test_only_production_code_is_synchronized(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "task/refactor-workspace"
            source_file = source / "feature/src/main/ets/Foo.ets"
            mirror_file = mirror / "feature/src/main/ets/Foo.ets"
            source_file.parent.mkdir(parents=True)
            mirror_file.parent.mkdir(parents=True)
            source_file.write_text("before", encoding="utf-8")
            mirror_file.write_text("after", encoding="utf-8")
            self.assertEqual(0, _sync_production_changes(mirror, source))
            self.assertEqual("after", source_file.read_text(encoding="utf-8"))
            baseline = mirror.parent / "baseline-production/feature/src/main/ets/Foo.ets"
            self.assertEqual("before", baseline.read_text(encoding="utf-8"))

    def test_hvigor_generated_build_profile_does_not_reject_source_changes(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "task/refactor-workspace"
            source_file = source / "feature/src/main/ets/Foo.ets"
            mirror_file = mirror / "feature/src/main/ets/Foo.ets"
            generated = mirror / "feature/BuildProfile.ets"
            source_file.parent.mkdir(parents=True)
            mirror_file.parent.mkdir(parents=True)
            generated.parent.mkdir(parents=True, exist_ok=True)
            source_file.write_text("before", encoding="utf-8")
            mirror_file.write_text("after", encoding="utf-8")
            generated.write_text("generated by hvigor", encoding="utf-8")

            self.assertEqual(0, _sync_production_changes(mirror, source))
            self.assertEqual("after", source_file.read_text(encoding="utf-8"))
            self.assertFalse((source / "feature/BuildProfile.ets").exists())

    def test_hvigor_generated_lock_file_does_not_reject_source_changes(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "task/refactor-workspace"
            source_file = source / "feature/src/main/ets/Foo.ets"
            mirror_file = mirror / "feature/src/main/ets/Foo.ets"
            generated = mirror / "feature/oh-package-lock.json5"
            source_file.parent.mkdir(parents=True)
            mirror_file.parent.mkdir(parents=True)
            generated.parent.mkdir(parents=True, exist_ok=True)
            source_file.write_text("before", encoding="utf-8")
            mirror_file.write_text("after", encoding="utf-8")
            generated.write_text("generated by ohpm", encoding="utf-8")

            self.assertEqual(0, _sync_production_changes(mirror, source))
            self.assertEqual("after", source_file.read_text(encoding="utf-8"))
            self.assertFalse((source / "feature/oh-package-lock.json5").exists())

    def test_module_index_is_synchronized_as_production_source(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "task/refactor-workspace"
            source_file = source / "feature/Index.ets"
            mirror_file = mirror / "feature/Index.ets"
            source_file.parent.mkdir(parents=True)
            mirror_file.parent.mkdir(parents=True)
            source_file.write_text("export before", encoding="utf-8")
            mirror_file.write_text("export after", encoding="utf-8")

            self.assertEqual(0, _sync_production_changes(mirror, source))
            self.assertEqual("export after", source_file.read_text(encoding="utf-8"))

    def test_test_build_cache_is_excluded_from_refactor_workspace(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source"
            mirror = root / "mirror"
            main = source / "module/src/main/ets/Foo.ets"
            cache = source / "module/.test/default/cache/compiler.msgpack"
            for path in (main, cache):
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text("data", encoding="utf-8")
            _fresh_copy(source, mirror, exclude_tests=True)
            self.assertTrue((mirror / "module/src/main/ets/Foo.ets").exists())
            self.assertFalse((mirror / "module/.test").exists())

    def test_changed_line_detection_ignores_preexisting_linter_lines(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            before = root / "before.ets"
            after = root / "after.ets"
            before.write_text("old warning\nkeep\nbefore\n", encoding="utf-8")
            after.write_text("old warning\nkeep\nafter\n", encoding="utf-8")
            self.assertNotIn(1, _changed_current_lines(before, after))
            self.assertIn(3, _changed_current_lines(before, after))


if __name__ == "__main__":
    unittest.main()
